### ISSUE TITLE
Injecting `http.Body` freezes `apistar run`

### ISSUE THREAD

**Issue by RadoRado** [tomchristie/apistar#94] opened 2017-04-21 18:54 UTC
Decided to play around with the framework, have the following thing:

```python
from apistar import http


def welcome(body: http.Body):
    return {'message': 'Welcome to API Star!'}
```

Making a request:

```bash
$ curl -X POST -d "" http://localhost:8080/
```

Everything hangs. Nothing happens until I stop the `apistar run` server.

Added a breakpoint inside `Body.build` - the `environ['wsgi.input'].read()` actually hangs.

Using Python `3.5.2`.

**Comment by maziarz** [comment] 2017-04-21 18:57
Where is the rest of your code?

**Comment by maziarz** [comment] 2017-04-21 19:01
I was able to reproduce the same issue with:

```
from apistar import http, App, Route

def welcome(body: http.Body):
    return {'message': 'Welcome to API Star!'}

app = App(routes=[
    Route('/welcome/', 'POST', welcome),
])

```

**Comment by tomchristie** [comment] 2017-04-21 19:15
👀 yikes.

**Comment by tomchristie** [comment] 2017-04-21 19:22
We should be making sure we read the content-length header when it exists, and only consume that much from the stream. That'll almost certainly be the issue. I'm AFK right now. Wanna try issuing up a PR for that and also seeing if it fixes the issue in development?

**Comment by RadoRado** [comment] 2017-04-21 19:52
@tomchristie I'll be doing some travelling tommorow but once I get to the laptop, will give it a try :star: (if you are talking to me :smile: )

**Comment by jpadilla** [comment] 2017-04-21 20:04
Ran into this as well a couple of minutes ago, and have a PR coming up in a few, working on tests now

**Comment by RadoRado** [comment] 2017-04-21 20:08
According to this - <http://stackoverflow.com/questions/22894078/why-does-environwsgi-input-read-block-even-though-it-is-allowed-by-pep-333> - should be just read the `int(environ['CONTENT_LENGTH'])`

**Comment by jpadilla** [comment] 2017-04-21 20:09
@RadoRado yup!

**Comment by jpadilla** [comment] 2017-04-21 20:16
I'm still wondering why tests didn't catch this...

**Comment by tomchristie** [comment] 2017-04-21 20:18
Because in the tests we have a fixed size bytestream object, that read() returns from, but under the server the connection stays open and the stream doesn't close itself.

**Comment by jpadilla** [comment] 2017-04-21 20:20
@tomchristie got that now, thanks!

**Closed** 2017-04-21 20:51 UTC
Labels: Bug
